title: On the Shelf
description: A blog on the typography of books from different genres I found on
  my bookshelf.
header_text: Always Judge a Book by its Cover?
footer_text: Caitlin Eatwell
header_feature_image: ../uploads/unnamed.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
