title: Typography on my Bookshelf
description: A blog on the typography of books from different genres I found on
  my bookshelf.
header_text: Typography on my Bookshelf
footer_text: Caitlin Eatwell
header_feature_image: ../uploads/pages.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
