title: On the Shelf
description: A blog on the typography of books from different genres I found on
  my bookshelf.
header_text: Always Judge a Book by its Cover?
footer_text: Caitlin Eatwell
header_feature_image: ../uploads/bookshelf_auto_x2.jpg
bannerheight: 60vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
