title: On the Shelf
description: ""
header_text: Always Judge a Book by its Cover?
footer_text: Caitlin Eatwell
header_feature_image: ../uploads/blog-banner.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
items: []
